# Form implementation generated from reading ui file 'qt10.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication
import sys

class MiniCalculator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 607)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.substract_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.substract_button.setGeometry(QtCore.QRect(100, 10, 21, 21))
        self.substract_button.setObjectName("substract_button")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(80, 10, 21, 21))
        self.add_button.setObjectName("add_button")
        self.multiply_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.multiply_button.setGeometry(QtCore.QRect(120, 10, 21, 21))
        self.multiply_button.setObjectName("multiply_button")
        self.first_value = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_value.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.first_value.setObjectName("first_value")
        self.second_value = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.second_value.setGeometry(QtCore.QRect(150, 10, 113, 20))
        self.second_value.setObjectName("second_value")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.substract_button.setText(_translate("MainWindow", "-"))
        self.add_button.setText(_translate("MainWindow", "+"))
        self.multiply_button.setText(_translate("MainWindow", "*"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MiniCalculator()
    ex.show
    sys.exit(app.exec())